name: win_my_argument
description: An AI-powered app to help win arguments with academic sources.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Core
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  iconsax: ^0.0.8
  google_fonts: ^6.1.0
  flutter_tts: ^3.8.5
  http: ^1.1.0
  timeago: ^3.6.0
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  file_picker: ^6.1.1

  # Firebase
  firebase_core: ^3.8.1
  firebase_remote_config: ^5.2.0
  
  # UI
  flutter_animate: ^4.3.0
  cached_network_image: ^3.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

